---
abstract: "An LWP User Agent which records and plays back requests\nand responses."
author:
  - 'Edward Allen <ealleniii_at_cpan_dot_org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LWPx-Test-Recorder
requires:
  File::Slurp: 0
  LWP: 0
  Test::More: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.3
